### ISSUE TITLE
[Feature] Support for restart on iOS

### ISSUE THREAD

**Issue by yanivshaked** [gabrimatic/restart_app#1]
Hi,

Do you have any plans to support restart on iOS?

Thanks

**Comment by gustavo-perini** [comment]
It would be great!!!

**Comment by swarupbhanjachowdhury** [comment]
Yes please add support

**Comment by gabrimatic** [comment]
I just added web support to the restart app package, so it now supports both Android and Web platforms.
But, in terms of iOS, I don't have any real plans since, before Flutter, I was an Android developer and, unfortunately, I have no expertise with iOS programming.
So, if you have any ideas, please share them with me or submit a fork request so that the package may have complete platform support.

**Comment by matekdk** [comment]
There are no methods available in iOS to restart the app. So the best that can be done on IOS is to re-instantiate root UIViewController. 

More info: https://stackoverflow.com/questions/66205648/is-there-any-way-to-restart-my-ios-app-programmatically

**Comment by msxenon** [comment]
I think in iOS you can only crash the app to stop it and you can't start it again

**Comment by gabrimatic** [comment]
> There are no methods available in iOS to restart the app. So the best that can be done on IOS is to re-instantiate root UIViewController.
> 
> More info: https://stackoverflow.com/questions/66205648/is-there-any-way-to-restart-my-ios-app-programmatically

I [tried](https://stackoverflow.com/questions/70548965/how-to-reregister-flutter-plugins-in-ios?noredirect=1#comment124711332_70548965) this method, and it has a big problem:
When I reassign the rootViewController with FlutterViewController, all the Flutter plugins are not available, and they need to register again.

**Comment by gabrimatic** [comment]
As my research and other developers suggestions, **there isn't any working solution for that**.
_I keep these threads open for new ideas._

**Comment by Milimeter** [comment]
Hi. Is it working on iOS now?

**Comment by khang-dev** [comment]
Any progress on this ?

**Comment by hosseinkhojany** [comment]
https://stackoverflow.com/a/66206070

**Comment by isAlmogK** [comment]
Following, need iOS support

**Comment by zamirszn** [comment]
its 2023 and no solution for iOS , has anyone been able to figure it out

**Comment by gabrimatic** [comment]
@Milimeter, @khang-dev, @hosseinkhojany, @isAlmogK, @zamirszn I appreciate your support and feedback on this package!

Unfortunately, restarting a Flutter app using native APIs in iOS is not supported by **the platform**.
However, you can look at [this StackOverflow answer](https://stackoverflow.com/a/66206070/9885611), or if you have a solution, do not hesitate to add it here.

_I keep this issue open for new ideas_

**Comment by zamirszn** [comment]
> @Milimeter, @khang-dev, @hosseinkhojany, @isAlmogK, @zamirszn I appreciate your support and feedback on this package!
> 
> Unfortunately, restarting a Flutter app using native APIs in iOS is not supported by **the platform**. However, you can look at [this StackOverflow answer](https://stackoverflow.com/a/66206070/9885611), or if you have a solution, do not hesitate to add it here.
> 
> _I keep this issue open for new ideas_

alright , thank alot

**Comment by gabrimatic** [comment]
After a very long period, iOS support has now been added to the restart_app package v1.2.0!
