### ISSUE TITLE
Not Restarting, just closes the app in android. 

### ISSUE THREAD

**Issue by Its-NK** [gabrimatic/restart_app#12]
I have just tested the package on the Android platform and it is not working as expected. 
it doe not Restart the app, but just closes the app in Android. then you will have to reOpen manually

**Comment by parthSanghani05** [comment]
i'm also having the same issue with 1.1.2 version

**Comment by li-xiaojun** [comment]
same issue

**Comment by Gilianp** [comment]
Same here

**Comment by pingtobuild** [comment]
same here
