### ISSUE TITLE
'No implementation found for method $method on channel $name'

### ISSUE THREAD

**Issue by iPypeNB** [gabrimatic/restart_app#13]
when I press the button to restart the application does not restart and the platform gives me the following error message

![image](https://github.com/gabrimatic/restart_app/assets/47798722/95c9370b-efe2-45ce-aef0-ca4643a18d2e)

No implementation found for method restartApp on channel restart

**Comment by Gilianp** [comment]
Me too! In android

**Comment by juliavi** [comment]
Rebuild from scratch should solve this error
