### ISSUE TITLE
App crash when call restart app

### ISSUE THREAD

**Issue by minhnguyenandpad** [gabrimatic/restart_app#15]
This no longer work on Android and iOS anymore. When we call restartApp. It crashed both on Android and iOS.

**Comment by blk-raffy** [comment]
Just tested and it works on both

**Comment by hussien8811** [comment]
same with me. Did you solve it for iOS?
flutter 3.10.0
restart_app 1.2.1

**Comment by juliavi** [comment]
It only crashes while in debug mode or running with the IDE.
When running separately on a device, it doesn't crash.

**Comment by PhaniUmmedisetti** [comment]
> same with me. Did you solve it for iOS? flutter 3.10.0 restart_app 1.2.1

The crashing issue is basically in debug mode only irrespective of the device. Raun it in release mode and it works just fine. In IOS it will close the app but you'll get a notification because there's issue with IOS's permission handler

**Comment by mohsinnaqvi0606** [comment]
Tested on IOS, it's still crashing in both mode release and debug.

Flutter: 3.13.0
restart_app: 1.2.1

**Comment by dnfield** [comment]
This is almost certainly due to https://github.com/gabrimatic/restart_app/issues/23

**Comment by gabrimatic** [comment]
https://github.com/gabrimatic/restart_app/issues/23#issuecomment-2331931090
