### ISSUE TITLE
How to set custom message on notification

### ISSUE THREAD

**Issue by maciogg** [gabrimatic/restart_app#17]
Is it possible to set custom message pon notification? I've app in many languages :)

**Comment by PhaniUmmedisetti** [comment]
is there a way to achieve this?

**Comment by PhaniUmmedisetti** [comment]
Fork this repo and change the sendNotification function. Change the title and body just like below 

<img width="735" alt="Screenshot 2023-09-01 at 12 08 55 PM" src="https://github.com/gabrimatic/restart_app/assets/100353755/20be2664-9ca9-4447-9c95-0d8f3237ef13">

**Comment by gabrimatic** [comment]
Now in the new version 1.3.0, you can customize the title and the body of the notification.
