### ISSUE TITLE
Does somebody has this exeption? "Execution failed for task ':restart_app:compileDebugKotlin'."

### ISSUE THREAD

**Issue by MartinBal97** [gabrimatic/restart_app#27]
I did an update of all of my packages and now I have this error:

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':restart_app:compileDebugKotlin'.
> 'compileDebugJavaWithJavac' task (current target is 1.8) and 'compileDebugKotlin' task (current target is 17) jvm target compatibility should be set to the same Java version.
  Consider using JVM toolchain: https://kotl.in/gradle/jvm/toolchain
  
  I have changed the current target as many people have done but I'm still having the error, if I delete restart_app from dependencies my app works fine.

**Comment by VickySalunkhe** [comment]
@MartinBal97  facing same issue, did you find any solution yet ?

**Comment by MartinBal97** [comment]
No, I didn't 😔, this happend to me also when I added stripe to my app, are you using stripe?

**Comment by VickySalunkhe** [comment]
No, i upgraded gradle and flutter version now stuck from last couple of days

**Comment by MartinBal97** [comment]
@VickySalunkhe Hi Vicky, were you able to solve the problem?

**Comment by VickySalunkhe** [comment]
> @VickySalunkhe Hi Vicky, were you able to solve the problem?

For now I have forked the package , and made changes to manage gradle and kotlin version
which seems to make it work, as of now.

You can try as well and let me know, if it works for you :)

```
restart_app:
    git:
      url: https://github.com/VickySalunkhe/restart_app.git
```

**Comment by MartinBal97** [comment]
I just create my andoid app folder again, it is not something only of restart_app it may happen with others packages too.

**Comment by VickySalunkhe** [comment]
> I just create my andoid app folder again, it is not something only of restart_app it may happen with others packages too.

so what was the final conclusion for you?

How did you make it work, as you said, i have faced the same errors wih multiple packages.
this temporary fix doesnt seem to work well.

**Comment by MartinBal97** [comment]
I do not have conclusion becouse I didn't fix it the way I would have liked. I'm agree with that is a temporary fix but I could't find other way to do it

**Comment by yangcheng** [comment]
While @VickySalunkhe 's fork works, I have other plugins have similar issue, so I override the kotlin jvmTarget in android project's `build.gradle` . It works for me now and buy me couple of weeks or months to upgrade all dependencies 

```gradle
    subprojects {
        afterEvaluate { project ->
            if (project.hasProperty('android')) {
                project.android {
                    if (namespace == null) {
                        namespace project.group
                    }
                }
            }
//Add this check
            if (project.plugins.hasPlugin('kotlin-android') || project.plugins.hasPlugin('kotlin')) {
                project.tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).all {
                    kotlinOptions {
                        jvmTarget = '1.8'
                    }
                }
            }
        }
    }
```

**Comment by bilalmuhammed99** [comment]
> > @VickySalunkhe Hi Vicky, were you able to solve the problem?
> 
> For now I have forked the package , and made changes to manage gradle and kotlin version which seems to make it work, as of now.
> 
> You can try as well and let me know, if it works for you :)
> 
> ```
> restart_app:
>     git:
>       url: https://github.com/VickySalunkhe/restart_app.git
> ```



> > @VickySalunkhe Hi Vicky, were you able to solve the problem?
> 
> For now I have forked the package , and made changes to manage gradle and kotlin version which seems to make it work, as of now.
> 
> You can try as well and let me know, if it works for you :)
> 
> ```
> restart_app:
>     git:
>       url: https://github.com/VickySalunkhe/restart_app.git
> ```

thank you thats work for me
