### ISSUE TITLE
Compatibility Issue: Plugin Incompatible with Latest App and Firebase Versions

### ISSUE THREAD

**Issue by ZeeshanSalem** [gabrimatic/restart_app#33]
I'm encountering a compatibility issue with a custom plugin when integrating it with the latest app and Firebase versions. The build fails due to a mismatch between the Java and Kotlin target versions (Java 1.8 vs. Kotlin 17) and conflicts with the Firebase dependencies. The plugin needs to be updated to align with the app's configuration, including the JVM target version and Firebase library versions, to ensure it compiles and runs correctly.

Also facing conflict with firebase plugins.

**Comment by gabrimatic** [comment]
The new version 1.3.1 now includes the related fixes.
