### ISSUE TITLE
 Android Can not restart just close

### ISSUE THREAD

**Issue by BeiAduo** [gabrimatic/restart_app#8]
[✓] Flutter (Channel stable, 3.3.10, on macOS 13.0.1 22A400 darwin-arm, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] Android Studio (version 2021.3)
[✓] Android Studio (version 2021.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.3.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.3.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.2.3)
[✓] VS Code (version 1.74.3)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

same times ------------------------------------------------------------

I/Timeline(12382): Timeline: Activity_launch_request time:59583698
I/.app_dopemv_co(12382): System.exit called, status: 0
I/AndroidRuntime(12382): VM exiting with result code 0, cleanup skipped.

same times ------------------------------------------------------------

I/Timeline( 9571): Timeline: Activity_launch_request time:58736647
I/.app_dopemv_co( 9571): System.exit called, status: 0
I/AndroidRuntime( 9571): VM exiting with result code 0, cleanup skipped.
Lost connection to device.
Failed to send request: {"jsonrpc":"2.0","id":"59","method":"getMemoryUsage","params":{"isolateId":"isolates/2620283676538703"}}

**Comment by nam-tu** [comment]
make sure you are not in debug mode

**Comment by gabrimatic** [comment]
@BeiAduo Package has been updated to Flutter 3.10
I will keep the issue open for a while to ensure that no related bugs appear before closing it.
